name: Talend Job

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy changelog.xml with adjusted permissions
        run: |
          mkdir .\temp
          copy "C:\Program Files (x86)\TOS_DI-8.0.1\studio\workspace\LOCAL_PROJECT\poms\jobs\process\demo\simple_0.1\src\main\resources\changelog.xml" .\temp
          icacls .\temp\changelog.xml /grant:r Users:R
      - name: Compile and Run Java Code
        run: |
          cd "C:\Program Files (x86)\TOS_DI-8.0.1\studio\workspace\LOCAL_PROJECT\poms\jobs\process\demo\simple_0.1\src\main\java"
          javac -cp "C:\Program Files (x86)\TOS_DI-8.0.1\studio\workspace\LOCAL_PROJECT\poms\jobs\process\demo\simple_0.1\lib/*" local_project/simple_0_1/simple.java
          java -cp "C:\Program Files (x86)\TOS_DI-8.0.1\studio\workspace\LOCAL_PROJECT\poms\jobs\process\demo\simple_0.1\lib/*;." local_project.simple_0_1.simple
